### ISSUE TITLE
Factory clock color

### ISSUE THREAD

**Issue by kirk5275** [Xinyuan-LilyGO/T-QT#10]
How can I change the colors of the clock? Background, hands etc.?

**Comment by kirk5275** [comment]
My Display is mostly gray with white letters. Second hand is yellowish orange.

**Comment by LilyGO** [comment]
please attach your picture

**Comment by kirk5275** [comment]
![image](https://user-images.githubusercontent.com/59910947/183708761-fef1c056-ca0b-45d8-bbb6-06e59c94926f.png)

No matter what camera I use the is a blue tint to the picture. I see all gray with my eyes.

**Comment by kirk5275** [comment]
![image](https://user-images.githubusercontent.com/59910947/183716222-cd860db1-7715-47a8-904f-e22b5bb0133b.png)
Here is a better representation.

**Comment by kirk5275** [comment]
![image](https://user-images.githubusercontent.com/59910947/183718291-a6d6aa09-b6b9-4ee5-b1d4-58915bbc7193.png)

**Comment by LilyGO** [comment]
Abnormal display color is generally caused by several problems.
1. RGB and BGR display format settings are wrong.
2. The order of sending color buf is reversed.
3. The colors are set to invert.

  Select a normal color image to convert to an array and display the image using the provided TFT_eSPI library. If the display is normal, record the picture display format as RGB or BGR. reconstruct

**Comment by kirk5275** [comment]
Just want to say that the duck looks okay. Green background white duck yellow beak and orange feet.

I am using your factory example with no modifications. Why should I have to change anything to get the colors to come out correctly? Also I don't know how to do do what you told me. 

Again might I have a bad unit?

**Comment by LilyGO** [comment]
If duck color is green background white duck yellow beak and orange feet. Then its color is normal.

**Comment by kirk5275** [comment]
Okay. I might have wasted your time and you mine. The one with blue clock is in \T-QT-main\lib\TFT_eSPI\examples\Smooth Graphics\Anti-aliased_Clock.

**Comment by LilyGO** [comment]
This obviously has nothing to do with the hardware. It may just be that a register needs to be modified during initialization or that it needs to be high first when sending color BUF.

**Comment by kirk5275** [comment]
I am closing this as I don't have a color problem
