### ISSUE TITLE
Missing lv_conf.h

### ISSUE THREAD

**Issue by tyeth** [Xinyuan-LilyGO/T-QT#12]
Hi, I just happened to luckily buy the T-Display-S3 at the same time as the T-QT. The T-Display repo has the lv_conf.h in the lib folder, which is missing from this repo.

Error message was:
```
**TRUNCATED**libraries/lvgl/src/../src/misc/../lv_conf_internal.h:41:18: fatal error: ../../lv_conf.h: No such file or directory
         #include "../../lv_conf.h"                /*Else assume lv_conf.h is next to the lvgl folder*/
```

**Comment by LilyGO** [comment]
https://github.com/Xinyuan-LilyGO/T-QT/blob/main/lib/lvgl/lv_conf.h
Documentation is here. Please drag this file to the same level as lvgl.

**Comment by LilyGO** [comment]
Problem has been resolved.
