### ISSUE TITLE
Publish board settings for Arduino IDE

### ISSUE THREAD

**Issue by HowdyMoto** [Xinyuan-LilyGO/T-QT#14]
Can you please publish what settings I should use here in the Arduino IDE?
![Screenshot 2022-10-21 141854](https://user-images.githubusercontent.com/43309236/197290351-940071e8-6dd3-4579-8b0b-878b84605b9a.png)

**Comment by LilyGO** [comment]
Just select ESP32-S3-DEV. Most of the other options vary based on individual usage.

**Comment by mmMicky** [comment]
![image](https://user-images.githubusercontent.com/63094275/203451936-21ff64ac-f35a-413f-a9ec-a9e934758a9b.png)

**Comment by afpineda** [comment]
Note:

In order to **enter boot mode**, press and hold the `IO0` button while pressing the `RESET` button.

**Comment by MichaelCastano** [comment]
> Note:
> 
> If required, in order to **enter boot mode**, press and hold the `IO0` button while pressing the `RESET` button.

Had problems connection on Windows 11 and that one hint solved it for me in the end 👍  Thanks
On MacOs it worked right out of the box following the Lilygo instructions.
