### ISSUE TITLE
T-QT Pro? 

### ISSUE THREAD

**Issue by dskw** [Xinyuan-LilyGO/T-QT#15]
Hi, I have noticed that a lot of stores offer a "T-QT Pro" version instead of V1.1.
The only difference I could find is this image:
https://ae01.alicdn.com/kf/S24bd6ed3ecd24f09878124b287e865efs.jpg_640x640Q90.jpg_.webp

Is there an updated repository for the Pro version?
What does "support charging" mean? Does it allow LiPo charging?

**Comment by LilyGO** [comment]
>Is there an updated repository for the Pro version?
There are no new warehouses. They share a repository, the only difference is the difference in hardware (psram and flash size)

>What does "support charging" mean? Does it allow LiPo charging?
Yes, it supports lithium battery charging.

**Comment by dskw** [comment]
Thank you for the clarification! I would suggest to add a short section to the readme.rm to describe the new version. The added lithium battery charging makes the board even more attractive! :)

**Comment by Vadimledyaev** [comment]
Hi, what cha
