### ISSUE TITLE
What settings for factory example?

### ISSUE THREAD

**Issue by matterbury** [Xinyuan-LilyGO/T-QT#16]
With the default settings compilation fails with:
```
Sketch uses 1379037 bytes (105%) of program storage space. Maximum is 1310720 bytes.
Global variables use 41472 bytes (12%) of dynamic memory, leaving 286208 bytes for local variables. Maximum is 327680 bytes.
```
With Flash Size of 8MB (64 Mb) and Partition Scheme 8M with spiffs the device just crash reboots.

**Comment by matterbury** [comment]
In fact it would be very helpful to have some idea of which examples work on the T-S3 board and what settings are needed for them. So far I'm about 3 for 8 working with the rest just blank screen or crash booting.

**Comment by mmMicky** [comment]
T-QT is a flash size of 8M. T-QT PRO has 4M flash size and 2M PSRAM. You can set the partition table for storing programs slightly larger. E.g ![image](https://user-images.githubusercontent.com/63094275/203451679-df1b11db-94d5-4c3f-8542-03659ac44fc5.png)

**Comment by mmMicky** [comment]
![image](https://user-images.githubusercontent.com/63094275/203451799-c79c2d9b-f96d-4d77-8bdc-8a455df277d2.png)

**Comment by matterbury** [comment]
Thanks, but as far as I can tell the factory example just does not work on the T-S3.
Many of the TFT_ ones do so I can play with those.

**Comment by mmMicky** [comment]
It works fine on my computer. I wonder why your run fails. I need to fix it.

**Comment by mmMicky** [comment]
I suggest you take a screenshot of the error or setting. I can help you check the problem.

**Comment by mmMicky** [comment]
![image](https://user-images.githubusercontent.com/63094275/203880580-00ab213a-6713-419a-8ca1-83b29fab498c.png)
Here you need to set none

**Comment by matterbury** [comment]
I set PSRAM to none and all the other settings as you have above.
Here is a video of the device while uploading, then a flash of the previous (clock) app when it rebooted, then the apparent crash looping after booting: https://www.dropbox.com/s/mhblk9lckomdqxq/IMG_0240.MOV?dl=0

Thanks for your help.

**Comment by mmMicky** [comment]
I thought you had a problem with the T-QT product. If you have a problem with T-Display-S3, you need to enable the PSRAM-OPI function. It is recommended that you clone the repository without modifying it and use platformIO to compile. Because I used this platform to make. So I recommend you to use it.

**Comment by mmMicky** [comment]
I can put the tested binary bin firmware here for you to burn and test.
[bin.zip](https://github.com/Xinyuan-LilyGO/T-QT/files/10095440/bin.zip)

**Comment by matterbury** [comment]
Thank you very much, OPI PSRAM did the trick!
