### ISSUE TITLE
Circuitpython Support - Requested USB PIDs done - Work In Progress

### ISSUE THREAD

**Issue by tyeth** [Xinyuan-LilyGO/T-QT#22]
I'm desperately keen to have this board supported in Circuitpython.
I've gone and added USB PID's after noticing the T-EmbedS3 was recently added https://github.com/espressif/usb-pids/pull/80
I've also defined the pins and done a working build, but no display tested yet so still work in progress.

If anyone has a further along repo or wants to contribute or just follow along then feel free.
Due to the GC9107 not being identical to the ST7789, I've not even begun to play with initialisation and it may just require minor tweaks, but I've included some code duplicated from the adafruit reverse s3 tft board. A clear way forwards is to use  russhughes repo's for both the T-QT and T-DisplayS3 display drivers in micropython. 

https://github.com/tyeth/circuitpython/tree/add-lilygo_ttgo_t-qt

Might save someone else a little time.

**Comment by lewisxhe** [comment]
Thank you for your contribution
