### ISSUE TITLE
I want to build this project under esp-idf,what can i do

### ISSUE THREAD

**Issue by weiqifa0** [Xinyuan-LilyGO/T-QT#24]
hi,i want to build this under esp-idf

**Comment by weiqifa0** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/11375905/225691353-2d67f669-588c-42b4-92a7-101d96930a5d.png">

**Comment by weiqifa0** [comment]
I can't use esp-idf driver the lcd

**Comment by lewisxhe** [comment]
I cannot provide code that can be run directly The IDF example directory contains related examples of spi lcds. Please refer to their implementation methods

**Comment by weiqifa0** [comment]
but under ardunio ,what project can i open ?

**Comment by weiqifa0** [comment]
哥们，能不能加个微信？

**Comment by weiqifa0** [comment]
哥们，微信能不能加一个？




郁闷少年O(∩_∩)O~~
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xinyuan-LilyGO/T-QT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 上午7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xinyuan-LilyGO/T-QT] I want to build this project under esp-idf,what can i do (Issue #24)





 
哥们，示例我全部更新过了，你重新克隆仓库吧。
