### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by robcloot** [Xinyuan-LilyGO/T-QT#30]
I can upload the following sketch, and the serial monitor works, but nothing displays on the T-QT screen.

#include <TFT_eSPI.h>
TFT_eSPI tft = TFT_eSPI();

void setup()
{
 Serial.begin(115200);
 tft.init();
 tft.fillScreen(TFT_BLACK);
}

void loop()
{
 tft.println("Hello World");
 Serial.println("Hello World");
 delay(1000);
 }

**Comment by lewisxhe** [comment]
See [QuickStart](https://github.com/Xinyuan-LilyGO/T-QT/tree/f298282b1837a90fad4f1722d082405742ea0077#quick-start) and Tips

**Comment by robcloot** [comment]
Yes lewisxhe, that fixed the problem.  I needed to  use the TFT_eSPI settings for T-QT in GitHub.  Thank you so much!
