### ISSUE TITLE
Bought 3 - 0 work

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [Xinyuan-LilyGO/T-QT#4]
Can someone tell me what the magic is to get these to work? I am using a Mac and tried multiple USB-C cables. None of the units power up or appear available in PIO.

What is the secret?

**Comment by mgsb** [comment]
I had the same problem. What works for me is to use a USB-A cable on the host side, even if it means a USB-C/USB-A adaptor for the host. I asked elsewhere for LILYGO feedback but have not heard anything, yet.

**Comment by LilyGO** [comment]
Please use a USBA-USBC cable. The use of USBC-USBC is not currently supported.
